# docker-compose.yml

version: "3.2"
services:
  rg:
    container_name: rg
    image: redislabs/redisgears
    ports:
        - "6379:6379"

  redisinsight:
    container_name: insight
    image: redislabs/redisinsight
    ports:
        - "8001:8001"

