# docker-compose.yml

version: "3.2"
services:
  redis:
    container_name: redis-cont
    image: "redis:alpine"
    command: redis-server
    environment:
        - REDIS_REPLICATION_MODE=master
    ports:
        - "6379:6379"
    volumes:
        # 数据存到当前目录
        - ./redis-data:/data
    command:
        # Save if 100 keys are added in every 10 seconds
        - "--save 10 100"
        # - "--requirepass ubuntu"

  redisinsight:
    container_name: redisinsight-cont
    image: redislabs/redisinsight
    ports:
        - 0.0.0.0:8001:8001
    volumes:
        - redisinsight:/db

volumes:
  redis-data:
  redisinsight:
